export const dataTableMembers = [
        { _id: 'name', label: 'Nombre y Apellido', align: 'center' },
        { _id: 'profile', label: 'Perfil', align: 'center' },
        { _id: 'team', label: 'Equipos', align: 'center' },
        { _id: 'language', label: 'Idiomas', align: 'center' },
        { _id: '' },
    ]


export const dataRolesBelbin = [
    { group: 'Roles de Acción', _id:'implementador' , name: 'Implementador', description: 'Los implementadores también son miembros del equipo que tienden a las acción, mantienen el orden en sus ambientes de trabajo. Son prácticos y excelentes para llevar las _ideas a buen puerto. Si bien a los implementadores les gusta la acción, también son muy disciplinados. Este tipo de indiv_iduos pueden ser la columna vertebral de un equipo porque son capaces de respaldar con confianza a otros compañeros.'},
    { group: 'Roles de Acción', _id:'impulsor' , name: 'Impulsor', description: 'Los impulsores son los miembros del equipo que hacen que el grupo avance. Son personas de acción, se motivan solos y también motivan a otros pese a cualquier inconveniente que pueda surgir. Los impulsores son líderes naturales. Cuando se produce una crisis encuentran ráp_idamente una solución'},
    { group: 'Roles de Acción', _id:'finalizador' , name: 'Finalizador', description: 'El último de los roles de acción es el de finalizador. Fiel al nombre, los finalizadores son personas dedicadas que trabajan intensamente para descubrir pequeños detalles y buscar la perfección. Estos miembros del equipo pueden ser más introvert_idos, pero son muy valiosos en el ámbito laboral porque son quienes empujan a los demás miembros del equipo a producir trabajos de alta cal_idad.'},
    { group: 'Roles Mentales', _id:'monitor-evaluador' , name: 'Monitor Evaluador', description: 'Otro rol mental dentro del equipo es el de monitor evaluador. Este tipo de personas son pensadores racionales y pueden hacer las emociones a un lado para resolver un problema. Los monitores evaluadores trabajan mejor cuando para los proyectos se necesita tener conocimientos profundos y un plan estratégico. Son quienes evalúan las _ideas para determinar si son útiles y viables, después toman las med_idas necesarias para hacer que esas _ideas avancen.'},
    { group: 'Roles Mentales', _id:'especialista' , name: 'Especialista', description: 'El último rol mental es el del especialista. Los especialistas conocen en profund_idad su campo de acción y prefieren contribuir en un área de especialización específica. Los especialistas siguen el mismo patrón que todos los roles mentales, en los que, en cierto modo, se trabaja mejor en soledad que en grupo. Pero a pesar de ser más independientes, aportan un gran valor al equipo con sus habil_idades específicas.'},
    { group: 'Roles Mentales', _id:'cerebro' , name: 'Cerebro', description: 'El cerebro es un miembro del equipo que tiene un rol mental, es innovador y creativo. Si bien los cerebros ayudan a equilibrar el equipo, prefieren trabajar con lluvias de _ideas y afianzar sus propias _ideas antes de compartirlas con el resto del equipo. Los cerebros prefieren trabajar solos, pero sus aportes son muy valiosos aunque no sean tan verborrágicos como otros miembros del grupo.'},
    { group: 'Roles Sociales', _id:'investigador-recursos' , name: 'Investigador de Recursos', description: 'El último de los nueve roles del equipo es el de investigador de recursos. Tienen habil_idades sociales y disfrutan de explorar opciones nuevas como las de encontrar oportun_idades de mercados potenciales para la empresa o de charlar con los interesados en los casos de lanzamientos de productos. Su actitud positiva es la que los convierte en generadores naturales de relaciones o facilitadores natos de negocios nuevos.'},
    { group: 'Roles Sociales', _id:'cohesionador' , name: 'Cohesionador', description: 'Los cohesionadores también pertenecen al grupo de los roles sociales. La personal_idad extrovert_ida los ayuda a funcionar bien con otras personas y a escuchar a sus compañeros de equipo. Estos miembros del equipo pueden adaptarse fácilmente a los cambios en el entorno y saben cómo armonizar cuando surge algún conflicto. Si un miembro del equipo tiene demasiado trabajo por hacer o si alguien tiene una emergencia familiar, los cohesionadores son los primeros en ocuparse y ofrecer ayuda.'},
    { group: 'Roles Sociales', _id:'coordinador' , name: 'Coordinador', description: 'Avanzamos para centrarnos en los roles sociales. El coordinador es un integrante del equipo con excelentes habil_idades comunicacionales. Los coordinadores, por lo general, ocupan puestos directivos porque son quienes promueven la colaboración y motivan al equipo para que se cumplan los objetivos. Los demás miembros del equipo respetan a los coordinadores y confían en sus decisiones.'},
]    
