
export const dataCountries = [
  { id: 'AD', name: 'Andorra'},
  {
    id: 'AE',
    name: 'United Arab Emirates',
    phone: '971',
  },
  { id: 'AF', name: 'Afghanistan'},
  {
    id: 'AG',
    name: 'Antigua and Barbuda',
    phone: '1-268',
  },
  { id: 'AI', name: 'Anguilla'},
  { id: 'AL', name: 'Albania'},
  { id: 'AM', name: 'Armenia'},
  { id: 'AO', name: 'Angola'},
  { id: 'AQ', name: 'Antarctica'},
  { id: 'AR', name: 'Argentina'},
  { id: 'AS', name: 'American Samoa'},
  { id: 'AT', name: 'Austria'},
  {
    id: 'AU',
    name: 'Australia',
    phone: '61',
    suggested: true,
  },
  { id: 'AW', name: 'Aruba'},
  { id: 'AX', name: 'Alland Islands'},
  { id: 'AZ', name: 'Azerbaijan'},
  {
    id: 'BA',
    name: 'Bosnia and Herzegovina',
    phone: '387',
  },
  { id: 'BB', name: 'Barbados'},
  { id: 'BD', name: 'Bangladesh'},
  { id: 'BE', name: 'Belgium'},
  { id: 'BF', name: 'Burkina Faso'},
  { id: 'BG', name: 'Bulgaria'},
  { id: 'BH', name: 'Bahrain'},
  { id: 'BI', name: 'Burundi'},
  { id: 'BJ', name: 'Benin'},
  { id: 'BL', name: 'Saint Barthelemy'},
  { id: 'BM', name: 'Bermuda'},
  { id: 'BN', name: 'Brunei Darussalam'},
  { id: 'BO', name: 'Bolivia'},
  { id: 'BR', name: 'Brazil'},
  { id: 'BS', name: 'Bahamas'},
  { id: 'BT', name: 'Bhutan'},
  { id: 'BV', name: 'Bouvet Island'},
  { id: 'BW', name: 'Botswana'},
  { id: 'BY', name: 'Belarus'},
  { id: 'BZ', name: 'Belize'},
  {
    id: 'CA',
    name: 'Canada',
    phone: '1',
    suggested: true,
  },
  {
    id: 'CC',
    name: 'Cocos (Keeling) Islands',
    phone: '61',
  },
  {
    id: 'CD',
    name: 'Congo, Democratic Republic of the',
    phone: '243',
  },
  {
    id: 'CF',
    name: 'Central African Republic',
    phone: '236',
  },
  {
    id: 'CG',
    name: 'Congo, Republic of the',
    phone: '242',
  },
  { id: 'CH', name: 'Switzerland'},
  { id: 'CI', name: "Cote d'Ivoire"},
  { id: 'CK', name: 'Cook Islands'},
  { id: 'CL', name: 'Chile'},
  { id: 'CM', name: 'Cameroon'},
  { id: 'CN', name: 'China'},
  { id: 'CO', name: 'Colombia'},
  { id: 'CR', name: 'Costa Rica'},
  { id: 'CU', name: 'Cuba'},
  { id: 'CV', name: 'Cape Verde'},
  { id: 'CW', name: 'Curacao'},
  { id: 'CX', name: 'Christmas Island'},
  { id: 'CY', name: 'Cyprus'},
  { id: 'CZ', name: 'Czech Republic'},
  {
    id: 'DE',
    name: 'Germany',
    phone: '49',
    suggested: true,
  },
  { id: 'DJ', name: 'Djibouti'},
  { id: 'DK', name: 'Denmark'},
  { id: 'DM', name: 'Dominica'},
  {
    id: 'DO',
    name: 'Dominican Republic',
    phone: '1-809',
  },
  { id: 'DZ', name: 'Algeria'},
  { id: 'EC', name: 'Ecuador'},
  { id: 'EE', name: 'Estonia'},
  { id: 'EG', name: 'Egypt'},
  { id: 'EH', name: 'Western Sahara'},
  { id: 'ER', name: 'Eritrea'},
  { id: 'ES', name: 'Spain'},
  { id: 'ET', name: 'Ethiopia'},
  { id: 'FI', name: 'Finland'},
  { id: 'FJ', name: 'Fiji'},
  {
    id: 'FK',
    name: 'Falkland Islands (Malvinas)',
    phone: '500',
  },
  {
    id: 'FM',
    name: 'Micronesia, Federated States of',
    phone: '691',
  },
  { id: 'FO', name: 'Faroe Islands'},
  {
    id: 'FR',
    name: 'France',
    phone: '33',
    suggested: true,
  },
  { id: 'GA', name: 'Gabon'},
  { id: 'GB', name: 'United Kingdom'},
  { id: 'GD', name: 'Grenada'},
  { id: 'GE', name: 'Georgia'},
  { id: 'GF', name: 'French Guiana'},
  { id: 'GG', name: 'Guernsey'},
  { id: 'GH', name: 'Ghana'},
  { id: 'GI', name: 'Gibraltar'},
  { id: 'GL', name: 'Greenland'},
  { id: 'GM', name: 'Gambia'},
  { id: 'GN', name: 'Guinea'},
  { id: 'GP', name: 'Guadeloupe'},
  { id: 'GQ', name: 'Equatorial Guinea'},
  { id: 'GR', name: 'Greece'},
  {
    id: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    phone: '500',
  },
  { id: 'GT', name: 'Guatemala'},
  { id: 'GU', name: 'Guam'},
  { id: 'GW', name: 'Guinea-Bissau'},
  { id: 'GY', name: 'Guyana'},
  { id: 'HK', name: 'Hong Kong'},
  {
    id: 'HM',
    name: 'Heard Island and McDonald Islands',
    phone: '672',
  },
  { id: 'HN', name: 'Honduras'},
  { id: 'HR', name: 'Croatia'},
  { id: 'HT', name: 'Haiti'},
  { id: 'HU', name: 'Hungary'},
  { id: 'ID', name: 'Indonesia'},
  { id: 'IE', name: 'Ireland'},
  { id: 'IL', name: 'Israel'},
  { id: 'IM', name: 'Isle of Man'},
  { id: 'IN', name: 'India'},
  {
    id: 'IO',
    name: 'British Indian Ocean Territory',
    phone: '246',
  },
  { id: 'IQ', name: 'Iraq'},
  {
    id: 'IR',
    name: 'Iran, Islamic Republic of',
    phone: '98',
  },
  { id: 'IS', name: 'Iceland'},
  { id: 'IT', name: 'Italy'},
  { id: 'JE', name: 'Jersey'},
  { id: 'JM', name: 'Jamaica'},
  { id: 'JO', name: 'Jordan'},
  {
    id: 'JP',
    name: 'Japan',
    phone: '81',
    suggested: true,
  },
  { id: 'KE', name: 'Kenya'},
  { id: 'KG', name: 'Kyrgyzstan'},
  { id: 'KH', name: 'Cambodia'},
  { id: 'KI', name: 'Kiribati'},
  { id: 'KM', name: 'Comoros'},
  {
    id: 'KN',
    name: 'Saint Kitts and Nevis',
    phone: '1-869',
  },
  {
    id: 'KP',
    name: "Korea, Democratic People's Republic of",
    phone: '850',
  },
  { id: 'KR', name: 'Korea, Republic of'},
  { id: 'KW', name: 'Kuwait'},
  { id: 'KY', name: 'Cayman Islands'},
  { id: 'KZ', name: 'Kazakhstan'},
  {
    id: 'LA',
    name: "Lao People's Democratic Republic",
    phone: '856',
  },
  { id: 'LB', name: 'Lebanon'},
  { id: 'LC', name: 'Saint Lucia'},
  { id: 'LI', name: 'Liechtenstein'},
  { id: 'LK', name: 'Sri Lanka'},
  { id: 'LR', name: 'Liberia'},
  { id: 'LS', name: 'Lesotho'},
  { id: 'LT', name: 'Lithuania'},
  { id: 'LU', name: 'Luxembourg'},
  { id: 'LV', name: 'Latvia'},
  { id: 'LY', name: 'Libya'},
  { id: 'MA', name: 'Morocco'},
  { id: 'MC', name: 'Monaco'},
  {
    id: 'MD',
    name: 'Moldova, Republic of',
    phone: '373',
  },
  { id: 'ME', name: 'Montenegro'},
  {
    id: 'MF',
    name: 'Saint Martin (French part)',
    phone: '590',
  },
  { id: 'MG', name: 'Madagascar'},
  { id: 'MH', name: 'Marshall Islands'},
  {
    id: 'MK',
    name: 'Macedonia, the Former Yugoslav Republic of',
    phone: '389',
  },
  { id: 'ML', name: 'Mali'},
  { id: 'MM', name: 'Myanmar'},
  { id: 'MN', name: 'Mongolia'},
  { id: 'MO', name: 'Macao'},
  {
    id: 'MP',
    name: 'Northern Mariana Islands',
    phone: '1-670',
  },
  { id: 'MQ', name: 'Martinique'},
  { id: 'MR', name: 'Mauritania'},
  { id: 'MS', name: 'Montserrat'},
  { id: 'MT', name: 'Malta'},
  { id: 'MU', name: 'Mauritius'},
  { id: 'MV', name: 'Maldives'},
  { id: 'MW', name: 'Malawi'},
  { id: 'MX', name: 'Mexico'},
  { id: 'MY', name: 'Malaysia'},
  { id: 'MZ', name: 'Mozambique'},
  { id: 'NA', name: 'Namibia'},
  { id: 'NC', name: 'New Caledonia'},
  { id: 'NE', name: 'Niger'},
  { id: 'NF', name: 'Norfolk Island'},
  { id: 'NG', name: 'Nigeria'},
  { id: 'NI', name: 'Nicaragua'},
  { id: 'NL', name: 'Netherlands'},
  { id: 'NO', name: 'Norway'},
  { id: 'NP', name: 'Nepal'},
  { id: 'NR', name: 'Nauru'},
  { id: 'NU', name: 'Niue'},
  { id: 'NZ', name: 'New Zealand'},
  { id: 'OM', name: 'Oman'},
  { id: 'PA', name: 'Panama'},
  { id: 'PE', name: 'Peru'},
  { id: 'PF', name: 'French Polynesia'},
  { id: 'PG', name: 'Papua New Guinea'},
  { id: 'PH', name: 'Philippines'},
  { id: 'PK', name: 'Pakistan'},
  { id: 'PL', name: 'Poland'},
  {
    id: 'PM',
    name: 'Saint Pierre and Miquelon',
    phone: '508',
  },
  { id: 'PN', name: 'Pitcairn'},
  { id: 'PR', name: 'Puerto Rico'},
  {
    id: 'PS',
    name: 'Palestine, State of',
    phone: '970',
  },
  { id: 'PT', name: 'Portugal'},
  { id: 'PW', name: 'Palau'},
  { id: 'PY', name: 'Paraguay'},
  { id: 'QA', name: 'Qatar'},
  { id: 'RE', name: 'Reunion'},
  { id: 'RO', name: 'Romania'},
  { id: 'RS', name: 'Serbia'},
  { id: 'RU', name: 'Russian Federation'},
  { id: 'RW', name: 'Rwanda'},
  { id: 'SA', name: 'Saudi Arabia'},
  { id: 'SB', name: 'Solomon Islands'},
  { id: 'SC', name: 'Seychelles'},
  { id: 'SD', name: 'Sudan'},
  { id: 'SE', name: 'Sweden'},
  { id: 'SG', name: 'Singapore'},
  { id: 'SH', name: 'Saint Helena'},
  { id: 'SI', name: 'Slovenia'},
  {
    id: 'SJ',
    name: 'Svalbard and Jan Mayen',
    phone: '47',
  },
  { id: 'SK', name: 'Slovakia'},
  { id: 'SL', name: 'Sierra Leone'},
  { id: 'SM', name: 'San Marino'},
  { id: 'SN', name: 'Senegal'},
  { id: 'SO', name: 'Somalia'},
  { id: 'SR', name: 'Suriname'},
  { id: 'SS', name: 'South Sudan'},
  {
    id: 'ST',
    name: 'Sao Tome and Principe',
    phone: '239',
  },
  { id: 'SV', name: 'El Salvador'},
  {
    id: 'SX',
    name: 'Sint Maarten (Dutch part)',
    phone: '1-721',
  },
  {
    id: 'SY',
    name: 'Syrian Arab Republic',
    phone: '963',
  },
  { id: 'SZ', name: 'Swaziland'},
  {
    id: 'TC',
    name: 'Turks and Caicos Islands',
    phone: '1-649',
  },
  { id: 'TD', name: 'Chad'},
  {
    id: 'TF',
    name: 'French Southern Territories',
    phone: '262',
  },
  { id: 'TG', name: 'Togo'},
  { id: 'TH', name: 'Thailand'},
  { id: 'TJ', name: 'Tajikistan'},
  { id: 'TK', name: 'Tokelau'},
  { id: 'TL', name: 'Timor-Leste'},
  { id: 'TM', name: 'Turkmenistan'},
  { id: 'TN', name: 'Tunisia'},
  { id: 'TO', name: 'Tonga'},
  { id: 'TR', name: 'Turkey'},
  {
    id: 'TT',
    name: 'Trinidad and Tobago',
    phone: '1-868',
  },
  { id: 'TV', name: 'Tuvalu'},
  {
    id: 'TW',
    name: 'Taiwan, Republic of China',
    phone: '886',
  },
  {
    id: 'TZ',
    name: 'United Republic of Tanzania',
    phone: '255',
  },
  { id: 'UA', name: 'Ukraine'},
  { id: 'UG', name: 'Uganda'},
  {
    id: 'US',
    name: 'United States',
    phone: '1',
    suggested: true,
  },
  { id: 'UY', name: 'Uruguay'},
  { id: 'UZ', name: 'Uzbekistan'},
  {
    id: 'VA',
    name: 'Holy See (Vatican City State)',
    phone: '379',
  },
  {
    id: 'VC',
    name: 'Saint Vincent and the Grenadines',
    phone: '1-784',
  },
  { id: 'VE', name: 'Venezuela'},
  {
    id: 'VG',
    name: 'British Virgin Islands',
    phone: '1-284',
  },
  {
    id: 'VI',
    name: 'US Virgin Islands',
    phone: '1-340',
  },
  { id: 'VN', name: 'Vietnam'},
  { id: 'VU', name: 'Vanuatu'},
  { id: 'WF', name: 'Wallis and Futuna'},
  { id: 'WS', name: 'Samoa'},
  { id: 'XK', name: 'Kosovo'},
  { id: 'YE', name: 'Yemen'},
  { id: 'YT', name: 'Mayotte'},
  { id: 'ZA', name: 'South Africa'},
  { id: 'ZM', name: 'Zambia'},
  { id: 'ZW', name: 'Zimbabwe'},
]